name: Demo Virtual Machine
on: 
  push: 
    branches: [main]

jobs:
  build:
    name: Virtual Machine
    runs-on: ubuntu-latest
    steps:
    - name: checkout my codes
      uses: actions/checkout@v2
    - name: Print and list out content
      run: |
        ls
        echo hello there! 
    - name: Get remote hidden repo
      uses: actions/checkout@v2
      with:
        repository: rayjosong/GoTrackDemoSystemBasic
        path: remote
        token: ${{ secrets.GH_TOKEN }}
    - name: Show hidden file
      run: |
        cd remote
        ls
    - name: Setup Go environment
      uses: actions/setup-go@v3.5.0
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.19.3 # optional
        # Path to the go.mod or go.work file.
    - name: Go installed
      run: |
        go version
        go mod init 
        go test -v
    - if: ${{ failure() }}

      uses: dacbd/create-issue-action@main
      with:
        token: ${{ secrets.GH_TOKEN }}
        title: Action workflow failed.
        body: |
          ### Context
          [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
          Workflow name - `${{ github.workflow }}`
          Job -           `${{ github.job }}`
          status -        `${{ job.status }}`
        assignees: Lowkh
