name : Demo Virtual Machine
on:
  push:
    branches: [main]
    
jobs:
  build:
    name: Virtual Machine
    runs-on: ubuntu-latest
    steps:
    - name: checkout my codes
      uses: actions/checkout@v2
    - name: Print and list out content
      run: echo Hello There!
    - name: Get remote hidden repo
      uses: actions/checkout@v2
      with:
          repository: Lowkh2/GoTrackRemoteExample
          path: remote
          token: ${{ secrets.GOTRACK }}

    - name: Show hidden File
      run: |
        cd remote
        ls   
        cat mySecret.txt
    - name: Setup Go environment
      uses: actions/setup-go@v3.5.0
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.19.3 # optional
 
    - name: Install dependencies for GO
      run: |
        go mod init rayjosong/GoTrackDemoSystemBasic
        go get github.com/franela/goblin@latest
        go get github.com/tebeka/go2xunit 
        go test -v
        ls
        
    - name: Telegram Notify
      uses: appleboy/telegram-action@0.0.3
      with: 
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
        
    - if: ${{ failure()}}
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ github.token }}
        title: Action workflow failed.
        body: |
          ### Context
          [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
          Workflow name - `${{ github.workflow }}`
          Job -           `${{ github.job }}`
          status -        `${{ job.status }}`
        assignees: rayjosong
    
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        junit_files: "report.xml"    
        
        
