name: Demo Virtual Machine
on: 
  push: 
    branches: [main]

jobs:
  build:
    name: Virtual Machine
    runs-on: ubuntu-latest
    steps:
    - name: checkout my codes
      uses: actions/checkout@v2
    - name: Print and list out content
      run: |
        ls
        echo hello there! 
